package view;

import Frame.*;
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rog
 */
public class viewMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Mahasiswa
     */
    CardLayout cardLayout;
    public viewMahasiswa() {
        initComponents();
        System.out.println("View Jalan");
        cardLayout = (CardLayout)(Body.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccessMahasiswa = new javax.swing.JSplitPane();
        MenuMahasiswa = new javax.swing.JPanel();
        Profile = new javax.swing.JButton();
        DaftarMK = new javax.swing.JButton();
        DaftarNilai = new javax.swing.JButton();
        DaftarHadir = new javax.swing.JButton();
        Pembayaran = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        apps_name = new javax.swing.JLabel();
        card_name_greetings = new javax.swing.JPanel();
        first_name_greetings = new javax.swing.JLabel();
        detailMhs = new javax.swing.JPanel();
        NamaMhs = new javax.swing.JLabel();
        NimMhs = new javax.swing.JLabel();
        TahunMasuk = new javax.swing.JLabel();
        JurusanMhs = new javax.swing.JLabel();
        IpkMhs = new javax.swing.JLabel();
        TahunLulus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AccessMahasiswa.setDividerLocation(0);
        AccessMahasiswa.setDividerSize(0);

        MenuMahasiswa.setBackground(new java.awt.Color(67, 50, 103));

        Profile.setBackground(new java.awt.Color(67, 50, 103));
        Profile.setForeground(new java.awt.Color(67, 50, 103));
        Profile.setText("Profile Mahasiswa");
        Profile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Profile.setPreferredSize(new java.awt.Dimension(206, 104));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        DaftarMK.setBackground(new java.awt.Color(67, 50, 103));
        DaftarMK.setText("Daftar Mata Kuliah");
        DaftarMK.setBorder(null);
        DaftarMK.setBorderPainted(false);
        DaftarMK.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DaftarMK.setPreferredSize(new java.awt.Dimension(206, 104));
        DaftarMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarMKActionPerformed(evt);
            }
        });

        DaftarNilai.setBackground(new java.awt.Color(67, 50, 103));
        DaftarNilai.setText("Daftar Nilai");
        DaftarNilai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DaftarNilai.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DaftarNilai.setPreferredSize(new java.awt.Dimension(206, 104));

        DaftarHadir.setBackground(new java.awt.Color(67, 50, 103));
        DaftarHadir.setText("Daftar Kehadiran");
        DaftarHadir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DaftarHadir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DaftarHadir.setPreferredSize(new java.awt.Dimension(206, 104));

        Pembayaran.setBackground(new java.awt.Color(67, 50, 103));
        Pembayaran.setText("Pembayaran");
        Pembayaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Pembayaran.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Pembayaran.setPreferredSize(new java.awt.Dimension(206, 104));
        Pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PembayaranMouseClicked(evt);
            }
        });
        Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuMahasiswaLayout = new javax.swing.GroupLayout(MenuMahasiswa);
        MenuMahasiswa.setLayout(MenuMahasiswaLayout);
        MenuMahasiswaLayout.setHorizontalGroup(
            MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuMahasiswaLayout.createSequentialGroup()
                .addGroup(MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DaftarNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DaftarHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DaftarMK, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuMahasiswaLayout.setVerticalGroup(
            MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(DaftarNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(DaftarHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(DaftarMK, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        AccessMahasiswa.setLeftComponent(MenuMahasiswa);
        MenuMahasiswa.getAccessibleContext().setAccessibleDescription("");

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        apps_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        apps_name.setForeground(new java.awt.Color(102, 102, 102));
        apps_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apps_name.setText("SISTEM INFORMASI AKADEMIK MAHASISWA");

        card_name_greetings.setBackground(new java.awt.Color(153, 153, 255));

        first_name_greetings.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        first_name_greetings.setForeground(new java.awt.Color(255, 255, 255));
        first_name_greetings.setText("Hi, Bob");

        javax.swing.GroupLayout card_name_greetingsLayout = new javax.swing.GroupLayout(card_name_greetings);
        card_name_greetings.setLayout(card_name_greetingsLayout);
        card_name_greetingsLayout.setHorizontalGroup(
            card_name_greetingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_name_greetingsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(first_name_greetings, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_name_greetingsLayout.setVerticalGroup(
            card_name_greetingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_name_greetingsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(first_name_greetings, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        detailMhs.setBackground(new java.awt.Color(255, 255, 255));

        NamaMhs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NamaMhs.setForeground(new java.awt.Color(51, 51, 51));
        NamaMhs.setText("Nama");

        NimMhs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NimMhs.setForeground(new java.awt.Color(51, 51, 51));
        NimMhs.setText("NIM");

        TahunMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TahunMasuk.setForeground(new java.awt.Color(51, 51, 51));
        TahunMasuk.setText("Tahun Masuk");

        JurusanMhs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JurusanMhs.setForeground(new java.awt.Color(51, 51, 51));
        JurusanMhs.setText("Jurusan");

        IpkMhs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IpkMhs.setForeground(new java.awt.Color(51, 51, 51));
        IpkMhs.setText("IPK");

        TahunLulus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TahunLulus.setForeground(new java.awt.Color(51, 51, 51));
        TahunLulus.setText("Tahun Lulus");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("1119111");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Bob Hamilton");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Informatika");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("2019");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("-");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("3.7");

        javax.swing.GroupLayout detailMhsLayout = new javax.swing.GroupLayout(detailMhs);
        detailMhs.setLayout(detailMhsLayout);
        detailMhsLayout.setHorizontalGroup(
            detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailMhsLayout.createSequentialGroup()
                .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(detailMhsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailMhsLayout.createSequentialGroup()
                                .addComponent(IpkMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailMhsLayout.createSequentialGroup()
                                .addComponent(NamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailMhsLayout.createSequentialGroup()
                                .addComponent(JurusanMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailMhsLayout.createSequentialGroup()
                                .addComponent(TahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailMhsLayout.createSequentialGroup()
                                .addComponent(TahunLulus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(detailMhsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(detailMhsLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(NimMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );
        detailMhsLayout.setVerticalGroup(
            detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailMhsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JurusanMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunLulus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IpkMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(detailMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(detailMhsLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(NimMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apps_name, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
            .addComponent(card_name_greetings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(detailMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(apps_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(card_name_greetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Body.add(Dashboard, "FrameCard1");

        AccessMahasiswa.setRightComponent(Body);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(406, 406, 406)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessMahasiswa)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(346, 346, 346)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarMKActionPerformed
        // TODO add your handling code here:
        cardLayout.show(Body, "FrameCard2");
    }//GEN-LAST:event_DaftarMKActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        cardLayout.show(Body, "FrameCard1");
    }//GEN-LAST:event_ProfileActionPerformed

    private void PembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PembayaranMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane AccessMahasiswa;
    private javax.swing.JPanel Body;
    private javax.swing.JButton DaftarHadir;
    private javax.swing.JButton DaftarMK;
    private javax.swing.JButton DaftarNilai;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel IpkMhs;
    private javax.swing.JLabel JurusanMhs;
    private javax.swing.JPanel MenuMahasiswa;
    private javax.swing.JLabel NamaMhs;
    private javax.swing.JLabel NimMhs;
    private javax.swing.JButton Pembayaran;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel TahunLulus;
    private javax.swing.JLabel TahunMasuk;
    private javax.swing.JLabel apps_name;
    private javax.swing.JPanel card_name_greetings;
    private javax.swing.JPanel detailMhs;
    private javax.swing.JLabel first_name_greetings;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
