package Frame;

import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rog
 */
public class Mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Mahasiswa
     */
    CardLayout cardLayout;
    public Mahasiswa() {
        initComponents();
        cardLayout = (CardLayout)(FrameCard.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccessMahasiswa = new javax.swing.JSplitPane();
        MenuMahasiswa = new javax.swing.JPanel();
        Profile = new javax.swing.JButton();
        DaftarMK = new javax.swing.JButton();
        DaftarNilai = new javax.swing.JButton();
        DaftarHadir = new javax.swing.JButton();
        Pembayaran = new javax.swing.JButton();
        FrameCard = new javax.swing.JPanel();
        FrameCard2 = new javax.swing.JPanel();
        FCard2 = new javax.swing.JPanel();
        FrameCard1 = new javax.swing.JPanel();
        FCard1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuMahasiswa.setBackground(new java.awt.Color(67, 50, 103));

        Profile.setBackground(new java.awt.Color(67, 50, 103));
        Profile.setForeground(new java.awt.Color(67, 50, 103));
        Profile.setText("Profile Mahasiswa");
        Profile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Profile.setPreferredSize(new java.awt.Dimension(206, 104));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        DaftarMK.setBackground(new java.awt.Color(67, 50, 103));
        DaftarMK.setText("Daftar Mata Kuliah");
        DaftarMK.setBorder(null);
        DaftarMK.setBorderPainted(false);
        DaftarMK.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DaftarMK.setPreferredSize(new java.awt.Dimension(206, 104));
        DaftarMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarMKActionPerformed(evt);
            }
        });

        DaftarNilai.setBackground(new java.awt.Color(67, 50, 103));
        DaftarNilai.setText("Daftar Nilai");
        DaftarNilai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DaftarNilai.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DaftarNilai.setPreferredSize(new java.awt.Dimension(206, 104));

        DaftarHadir.setBackground(new java.awt.Color(67, 50, 103));
        DaftarHadir.setText("Daftar Kehadiran");
        DaftarHadir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DaftarHadir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DaftarHadir.setPreferredSize(new java.awt.Dimension(206, 104));

        Pembayaran.setBackground(new java.awt.Color(67, 50, 103));
        Pembayaran.setText("Pembayaran");
        Pembayaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Pembayaran.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Pembayaran.setPreferredSize(new java.awt.Dimension(206, 104));
        Pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PembayaranMouseClicked(evt);
            }
        });
        Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuMahasiswaLayout = new javax.swing.GroupLayout(MenuMahasiswa);
        MenuMahasiswa.setLayout(MenuMahasiswaLayout);
        MenuMahasiswaLayout.setHorizontalGroup(
            MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DaftarMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DaftarNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DaftarHadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuMahasiswaLayout.createSequentialGroup()
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuMahasiswaLayout.setVerticalGroup(
            MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuMahasiswaLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarMK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        AccessMahasiswa.setLeftComponent(MenuMahasiswa);
        MenuMahasiswa.getAccessibleContext().setAccessibleDescription("");

        FrameCard.setBackground(new java.awt.Color(255, 255, 255));
        FrameCard.setLayout(new java.awt.CardLayout());

        FrameCard2.setBackground(new java.awt.Color(255, 255, 255));

        FCard2.setBackground(new java.awt.Color(44, 33, 68));

        javax.swing.GroupLayout FCard2Layout = new javax.swing.GroupLayout(FCard2);
        FCard2.setLayout(FCard2Layout);
        FCard2Layout.setHorizontalGroup(
            FCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        FCard2Layout.setVerticalGroup(
            FCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FrameCard2Layout = new javax.swing.GroupLayout(FrameCard2);
        FrameCard2.setLayout(FrameCard2Layout);
        FrameCard2Layout.setHorizontalGroup(
            FrameCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameCard2Layout.setVerticalGroup(
            FrameCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCard2Layout.createSequentialGroup()
                .addComponent(FCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 693, Short.MAX_VALUE))
        );

        FrameCard.add(FrameCard2, "FrameCard2");

        FrameCard1.setBackground(new java.awt.Color(255, 255, 255));

        FCard1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout FCard1Layout = new javax.swing.GroupLayout(FCard1);
        FCard1.setLayout(FCard1Layout);
        FCard1Layout.setHorizontalGroup(
            FCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FCard1Layout.setVerticalGroup(
            FCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM INFORMASI AKADEMIK MAHASISWA");

        javax.swing.GroupLayout FrameCard1Layout = new javax.swing.GroupLayout(FrameCard1);
        FrameCard1.setLayout(FrameCard1Layout);
        FrameCard1Layout.setHorizontalGroup(
            FrameCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
            .addComponent(FCard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameCard1Layout.setVerticalGroup(
            FrameCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCard1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        FrameCard.add(FrameCard1, "FrameCard1");

        AccessMahasiswa.setRightComponent(FrameCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessMahasiswa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessMahasiswa)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarMKActionPerformed
        // TODO add your handling code here:
        cardLayout.show(FrameCard, "FrameCard2");
    }//GEN-LAST:event_DaftarMKActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        cardLayout.show(FrameCard, "FrameCard1");
    }//GEN-LAST:event_ProfileActionPerformed

    private void PembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PembayaranMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane AccessMahasiswa;
    private javax.swing.JButton DaftarHadir;
    private javax.swing.JButton DaftarMK;
    private javax.swing.JButton DaftarNilai;
    private javax.swing.JPanel FCard1;
    private javax.swing.JPanel FCard2;
    private javax.swing.JPanel FrameCard;
    private javax.swing.JPanel FrameCard1;
    private javax.swing.JPanel FrameCard2;
    private javax.swing.JPanel MenuMahasiswa;
    private javax.swing.JButton Pembayaran;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
